#ifndef CNC_HAL_OVERRIDES_H
#define CNC_HAL_OVERRIDES_H
#ifdef __cplusplus
extern "C"
{
#endif

#define S_CURVE_ACCELERATION_LEVEL 0

#define DISABLE_ALL_CONTROLS
#define DISABLE_ALL_LIMITS
#define DISABLE_PROBE

#define TOOL1 pen_servo
#define PEN_SERVO SERVO0
#define PEN_SERVO_LOW 130
#define PEN_SERVO_HIGH 200

#define DELAY_ON_RESUME_SPINDLE 0
#define DELAY_ON_SPINDLE_SPEED_CHANGE 0
#define DELAY_ON_RESUME_COOLANT 0

#define DISABLE_SETTINGS_MODULES
#define DISABLE_MULTISTREAM_SERIAL
#define DISABLE_RTC_CODE

#define ENABLE_STEPPERS_DISABLE_TIMEOUT

#ifdef __cplusplus
}
#endif
#endif
